AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:

  ExampleBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - BucketKeyEnabled: true
          ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      OwnershipControls:
        Rules:
        - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  EmptyExampleBucketOnDelete:
    Type: Custom::EmptyBucketOnDelete
    Properties:
      ServiceToken: !GetAtt EmptyBucketOnDelete.Arn
      BucketName: !Ref ExampleBucket

  EmptyBucketOnDelete:
    Type: AWS::Serverless::Function
    Properties:
      Architectures: [ arm64 ]
      CodeUri: src/
      Handler: empty_bucket_on_delete.custom_resource
      Runtime: python3.9
      Timeout: 30
      Environment:
        Variables:
          LOG_LEVEL: INFO
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - 's3:DeleteObjectVersion'
          - 's3:ListBucketVersions'
          Resource:
          - !Sub 'arn:${AWS::Partition}:s3:::${AWS::StackName}-*'
